[package]
name = "credstash"
version = "0.5.0"
description = "Credstash is a utility for managing credentials in the AWS cloud"
keywords = ["AWS", "Amazon", "Secret", "Encryption", "Security"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/psibi/rucredstash"
authors = ["Sibi Prabakaran <sibi@psibi.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rusoto_core = "0.42.0"
rusoto_dynamodb = "0.42.0"
rusoto_ec2 = "0.42.0"
rusoto_kms = "0.42.0"
rusoto_credential = "0.42.0"
rusoto_sts = "0.42.0"
ring = "0.16.9"
aes-ctr = "0.3.0"
bytes = "0.4.12"
base64 = "0.11.0"
hex = "0.3.1"
futures = "0.1.29"
tokio-core = "0.1"
either = "1.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "credstash"
path = "src/lib.rs"

[[bin]]
name = "rucredstash"
path = "src/main.rs"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'
